#define IR_CODE_VOL_U 0x490
#define IR_CODE_VOL_D 0xC90

#define IR_CODE_SELECT_EQ 0x1D0
#define IR_CODE_SET_UP 0x9A
#define IR_CODE_SET_DOWN 0x89A
#define IR_CODE_CHANGE_RESOUCE 0x55A

#define IR_CODE_CHANGE_RESOUCE_WAVE 0x5BA
#define IR_CODE_CHANGE_RESOUCE_FAVORITE 0xC7A
#define IR_CODE_CHANGE_RESOUCE_RADIO 0xE9A
#define IR_CODE_CHANGE_RESOUCE_BT 0x69A
#define IR_CODE_ON_OFF 0xA9A



#define IR_CODE_NUMBER_1 0x4BA
#define IR_CODE_NUMBER_2 0x83A
#define IR_CODE_NUMBER_3 0x63A
#define IR_CODE_NUMBER_4 0xF3A
#define IR_CODE_NUMBER_5 0xC5A
#define IR_CODE_NUMBER_6 0x6D5D


#define IR_CODE_PLAY_NEXT 0x445D
#define IR_CODE_PLAY_PREV 0x45D
#define IR_CODE_PLAY_PLAY 0xC5D








