#define DELAY_IR_RECEVICE 150
#define DELAY_IR_POST 50
#define DELAY_DISPLAY 500
#define DELAY_AUTO_SAVE 30000
#define DELAY_SEND_STATS 10000


#define DELAY_DISPLAY_OFF 60000

#define SET_MODE_IDL 0
#define SET_MODE_EQ1 1
#define SET_MODE_EQ2 2
#define SET_MODE_EQ3 3
#define SET_MODE_VOLUME 4

#define SET_MODE_RES_MYWAVE 101
#define SET_MODE_RES_MYFAVORITE 102
#define SET_MODE_RES_ONLINE 103

#define CONST_HTTP_TIMEOUT 30000

#define CONST_VOLUME_MIN 0
#define CONST_VOLUME_MAX 21
#define CONST_EQ_MIN -40
#define CONST_EQ_MAX 6

#define CONST_SCREEN_OFF 0
#define CONST_SCREEN_IDL 1
#define CONST_SCREEN_PLAY 2
#define CONST_SCREEN_SETTING 3

#define SITE_MAIN_URL "http://efx2k10gma.temp.swtest.ru/esp32/index.php?"

#define BT_HOST_NAME "ESP_Music"

#define MUTE_HOUR_MIN 9
#define MUTE_HOUR_MAX 20



